/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
