package ca.uwaterloo.ece.bicer;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class BICCollectorTest {
    @Test public void testSomeLibraryMethod() {
        
    	BICCollector runner = new BICCollector();
    	
    	//String [] args ={"-d","data/exampleBIChanges.txt", "-g", System.getProperty("user.home") + "/git/BICER"};
    	String [] args ={"-g",System.getProperty("user.home") + "/Documents/UW/ODP/projects/lucene/git/git",
    						"-s", "2010-09-12 00:00:00",
    						"-e", "2010-11-12 23:59:59",
    						"-b", System.getProperty("user.home") + "/Documents/UW/ODP/projects/lucene/lucene_bug_reports.txt"};
    	
    	runner.run(args);
    	
    	//assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
