package ca.uwaterloo.ece.bicer;
import org.junit.Test;

import ca.uwaterloo.ece.bicer.utils.Labeler;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class LabelerTest {
    @Test public void testSomeLibraryMethod() {
    	
    	String path = System.getProperty("user.home") + "/Documents/ODP/projects/lucene/";
    	
    	String pathToArff = path + "arffsOriginalWOTestCases/0/train.arff";
    	String classAttributeName = "500_Buggy?";
    	String positiveLabel = "1";
    	String pathToChangeIDSha1Pair = path + "change_id_sha1_thin_lucene.txt";
    	String pathToBIChanges = path + "biChanges.txt";
    	String pathToNewArff = path + "test.arff";
    	String startDate="2010-09-17";
    	String endDate="2010-10-23 23:59:59";
    	String lastDateForFixCollection="2010-11-28 23:59:59";
        
    	Labeler.relabelArff(pathToArff, classAttributeName, positiveLabel, pathToChangeIDSha1Pair, pathToBIChanges, pathToNewArff, startDate, endDate, lastDateForFixCollection);
    	
    	//assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
