package ca.uwaterloo.ece.bicer;
import org.junit.Test;

import ca.uwaterloo.ece.bicer.utils.Sanitizer;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class SanitizerTest {
    @Test public void testSomeLibraryMethod() {
        
    	Sanitizer ster = new Sanitizer();
    	
    	ster.sanitizer("/Users/JC/Documents/UW/ODP/projects/lucene/biChanges.txt", "/Documents/UW/ODP/projects/lucene/git/git");
    	
    	//assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
